# Generated by Django 2.2 on 2019-04-22 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keeperapp', '0002_category_categorydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='categorydata',
            options={'verbose_name_plural': 'CategoryData'},
        ),
        migrations.RemoveField(
            model_name='categorydata',
            name='user',
        ),
        migrations.AddField(
            model_name='categorydata',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_data', to='keeperapp.Category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(max_length=2000)),
                ('receipt', models.ImageField(blank=True, upload_to='receipts/')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_category', to='keeperapp.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_user', to='keeperapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=500)),
                ('theme', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
