# Generated by Django 2.2 on 2019-04-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0004_auto_20190423_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydata',
            name='name',
        ),
    ]
