# Generated by Django 2.2 on 2019-04-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0006_auto_20190423_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryData',
            new_name='CategoryInfo',
        ),
        migrations.AlterModelOptions(
            name='categoryinfo',
            options={'verbose_name_plural': 'CategoryInfo'},
        ),
    ]
