# Generated by Django 2.2 on 2019-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0007_auto_20190423_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='category',
            name='columns',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='category',
            name='options',
            field=models.CharField(max_length=500),
        ),
    ]
