# Generated by Django 2.2 on 2019-04-27 18:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0008_auto_20190424_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='options',
            field=jsonfield.fields.JSONField(max_length=2000),
        ),
    ]
