# Generated by Django 2.2 on 2019-04-27 18:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0009_auto_20190427_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='options',
            field=jsonfield.fields.JSONField(blank=True, max_length=2000),
        ),
    ]
