# Generated by Django 2.2 on 2019-04-27 18:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0010_auto_20190427_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='options',
            field=jsonfield.fields.JSONField(default='{}', max_length=2000),
        ),
    ]
