# Generated by Django 2.2 on 2019-05-06 04:54

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0012_auto_20190430_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='options',
            field=jsonfield.fields.JSONField(default='{"null":"null"}', max_length=2000),
        ),
        migrations.AlterField(
            model_name='categoryinfo',
            name='category',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category_data', to='keeperapp.Category'),
        ),
    ]
