# Generated by Django 2.2 on 2019-05-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keeperapp', '0016_auto_20190508_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfo',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_data', to='keeperapp.Category'),
        ),
        migrations.AlterField(
            model_name='categoryinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='categoryinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
